import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mikiri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh m-0">
      <body className={`antialiased h-dvh m-0`}>
        <div className="h-full">{children}</div>
      </body>
    </html>
  );
}
